<!--[if lt IE 9]> <script src="{{ asset('template/admin/metronic4.5.6/global/plugins/respond.min.js') }}"></script> <script src="{{ asset('template/admin/metronic4.5.6/global/plugins/excanvas.min.js') }}"></script> 
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/js.cookie.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') }}"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.blockui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{{ asset('template/admin/metronic4.5.6/apps/scripts/calendar.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/apps/scripts/inbox.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/apps/scripts/timeline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/apps/scripts/todo.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/apps/scripts/todo-2.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/amcharts.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/pie.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/radar.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/serial.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/themes/chalk.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/themes/light.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amcharts/themes/patterns.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/ammap/ammap.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/ammap/maps/js/worldLow.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/amcharts/amstockcharts/amstock.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/autosize/autosize.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/backstretch/jquery.backstretch.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootbox/bootbox.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-contextmenu/bootstrap-contextmenu.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-datepaginator/bootstrap-datepaginator.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js') }}"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-editable/inputs-ext/address/address.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-growl/jquery.bootstrap-growl.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-markdown/js/bootstrap-markdown.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-markdown/lib/markdown.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-modal/js/bootstrap-modal.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-pwstrength/pwstrength-bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-select/js/bootstrap-select.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-selectsplitter/bootstrap-selectsplitter.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-sessiontimeout/bootstrap-session-timeout.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-summernote/summernote.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-tabdrop/js/bootstrap-tabdrop.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-table/bootstrap-table.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-toastr/toastr.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-typeahead/bootstrap3-typeahead.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/clockface/js/clockface.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/codemirror/lib/codemirror.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/codemirror/mode/css/css.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/codemirror/mode/htmlmixed/htmlmixed.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/codemirror/mode/javascript/javascript.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/countdown/jquery.countdown.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/counterup/jquery.counterup.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/counterup/jquery.waypoints.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/cubeportfolio/js/jquery.cubeportfolio.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/dropzone/dropzone.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/echarts/echarts.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/excanvas.min.js') }}"></script> 
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/fancybox/source/jquery.fancybox.pack.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.axislabels.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.categories.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.crosshair.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.pie.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.resize.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flot/jquery.flot.stack.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/flowchart/flowchart.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/fuelux/js/spinner.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/fullcalendar/fullcalendar.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/gmaps/gmaps.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highcharts/js/highcharts.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highcharts/js/highcharts-3d.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highcharts/js/highcharts-more.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highmaps/js/modules/data.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highmaps/js/modules/map.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/highstock/js/highstock.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/holder.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/horizontal-timeline/horozontal-timeline.min.js') }}"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/horizontal-timeline/horozontal-timeline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/icheck/icheck.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/ion.rangeslider/js/ion.rangeSlider.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jcrop/js/jquery.color.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jcrop/js/jquery.Jcrop.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.input-ip-address-control-1.0.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.mockjax.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.pulsate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery.sparkline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-bootpag/jquery.bootpag.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-cookiebar/jquery.cookieBar.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js') }}"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/vendor/load-image.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-idle-timeout/jquery.idletimeout.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-idle-timeout/jquery.idletimer.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-knob/js/jquery.knob.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-minicolors/jquery.minicolors.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-multi-select/js/jquery.multi-select.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-nestable/jquery.nestable.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-notific8/jquery.notific8.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/jquery.vmap.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/jstree/dist/jstree.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/ladda/ladda.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/ladda/spin.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/moment.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/morris/morris.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/morris/raphael-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/nouislider/nouislider.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/nouislider/wNumb.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/pace/pace.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/plupload/js/plupload.full.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/raphael.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/respond.min.js') }}"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/select2/js/select2.full.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/typeahead/handlebars.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/global/plugins/typeahead/typeahead.bundle.min.js') }}" type="text/javascript"></script>

<script src="{{ asset('template/admin/metronic4.5.6/global/scripts/datatable.js') }}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="{{ asset('template/admin/metronic4.5.6/global/scripts/app.min.js') }}" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->


<!-- BEGIN THEME LAYOUT SCRIPTS -->

<!-- END THEME LAYOUT SCRIPTS -->
<script src="{{ asset('template/admin/metronic4.5.6/layouts/global/scripts/cookie-consent.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/layouts/global/scripts/quick-sidebar.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/layouts/layout/scripts/demo.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/layouts/layout/scripts/layout.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-amcharts.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-echarts.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-flotcharts.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-flowchart.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-google.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-highcharts.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-highmaps.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-highstock.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/charts-morris.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/coming-soon.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-maxlength.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-select.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-select-splitter.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-switch.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-tagsinput.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-bootstrap-touchspin.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-code-editors.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-color-pickers.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-context-menu.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-date-time-pickers.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-editors.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-form-tools.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-ion-sliders.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-knob-dials.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-multi-select.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-nouisliders.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-select2.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/components-typeahead.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/contact.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/dashboard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ecommerce-dashboard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ecommerce-orders.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ecommerce-orders-view.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ecommerce-products.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ecommerce-products-edit.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-dropzone.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-editable.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-fileupload.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-icheck.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-image-crop.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-input-mask.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-samples.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-validation.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-validation-md.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/form-wizard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/lock.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/lock-2.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/login.min.js') }}" type="text/javascript"></script>
{{-- <script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/login-4.min.js') }}" type="text/javascript"></script> --}}
{{-- <script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/login-5.min.js') }}" type="text/javascript"></script> --}}
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/maps-google.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/maps-vector.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portfolio-1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portfolio-2.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portfolio-3.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portfolio-4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portlet-ajax.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/portlet-draggable.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/profile.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/search.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-ajax.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-buttons.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-colreorder.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-editable.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-fixedheader.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-managed.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-responsive.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-rowreorder.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/table-datatables-scroller.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/timeline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-alerts-api.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-blockui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-bootbox.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-bootstrap-growl.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-buttons.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-confirmations.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-datepaginator.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-extended-modals.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-general.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-idletimeout.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-modals.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-nestable.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-notific8.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-session-timeout.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-toastr.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('template/admin/metronic4.5.6/pages/scripts/ui-tree.min.js') }}" type="text/javascript"></script>
